# Generated by Django 5.2.14 on 2026-06-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0002_alter_user_losekol_alter_user_mmr_alter_user_winkol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMR', models.PositiveIntegerField(db_index=True, default=1000)),
                ('WinKol', models.PositiveIntegerField(default=0)),
                ('LoseKol', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(through='users.GameStats', to='games.game'),
        ),
    ]
