# Generated by Django 5.2.14 on 2026-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('hintForAdmin', models.CharField(blank=True, null=True)),
                ('relateOnId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
