# Generated by Django 5.2.14 on 2026-06-01 21:08

import django.db.models.deletion
import playSessions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_alter_game_image_alter_game_relateonid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(default=playSessions.models.generate_code, editable=False, max_length=12, unique=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberInSession', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playSessions.playsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playsession',
            name='players',
            field=models.ManyToManyField(through='playSessions.SessionParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
