# Generated by Django 5.2.14 on 2026-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playSessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipants',
            name='mmrChange',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionparticipants',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
