# Generated by Django 5.2.14 on 2026-06-06 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playSessions', '0002_sessionparticipants_mmrchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
